### ISSUE TITLE
[REQ] option for ignorePath

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-linter#88]
Filing based around a discussion over in PSK with @abdonrd https://github.com/PolymerElements/polymer-starter-kit/pull/1018#discussion_r116822607

It would be great to have an `ignorePath` flag similar to eslint. Would be nice to be able to ignore paths like `build/` 
http://eslint.org/docs/user-guide/configuring#using-an-alternate-file

**Comment by FredKSchott** [comment]
+1. we could also just have lint ignore the build directory by default, independently of this feature. (I kind of think that this was the original intended behavior)

**Comment by stramel** [comment]
I just updated to `v1.1.0` of `polymer-cli` and it is still trying to lint the build directory. I will file a bug for that.

**Comment by bennypowers** [comment]
I've strung together some shell scripts which rsync in files in `environments/$CUSTOMER/$ENVIRONMENT/src` to `src/` depending on which (you guessed it) customer and env I'm building. polymer lint (and polymer ide) keep trying to lint the `environments` dir, which will fail because those files are just patches, not backed up by a full app.

So the ability to ignore files and paths would be very helpful for me.

**Comment by stramel** [comment]
Since the linter doesn't have a standalone CLI, I will consider this closed once https://github.com/Polymer/polymer-cli/pull/948 has been merged.
